In [2]:
# Importing dependencies and libraries
import pandas as pd
from pathlib import Path
%matplotlib inline

In [19]:
SP500_data = Path("SP500_close_data.csv")

portfolio_data = Path("raw_portfolio.csv")

SP500_df = pd.read_csv(SP500_data, index_col=0, parse_dates=True, infer_datetime_format=True)
portfolio_df = pd.read_csv(portfolio_data, index_col=0, parse_dates=True, infer_datetime_format=True)


SP500_df
#portfolio_df

                  Close
Date
2015-10-02  1951.359985
2015-10-05  1987.050049
2015-10-06  1979.920044
2015-10-07  1995.829956
2015-10-08  2013.430054
...                 ...
2020-09-25  3298.459961
2020-09-28  3351.600098
2020-09-29  3335.469971
2020-09-30  3363.000000
2020-10-01  3380.800049

[1259 rows x 1 columns]

In [20]:
#concat the df's

joint_portfolio = pd.concat([SP500_df, portfolio_df], axis='columns', join='outer')

joint_portfolio.dropna()

,Close,ORCL,SQ,NVDA,BABA,PFE,NFLX,CRM,GD,AMT,...,PSX,BLK,TROW,JNJ,UNH,MMM,UPS,ACN,PPG,NEE
2015-11-19,2081.239990,36.108597,13.070000,30.458263,77.870003,27.049994,120.220001,80.639999,130.626297,99.63,...,92.38,359.09,76.38,102.49,110.63,158.38,104.10,107.28,103.37,100.99
2015-11-20,2089.169922,36.404728,12.850000,30.722525,79.949997,26.957846,123.839996,80.989998,130.896194,100.49,...,91.67,362.46,76.37,102.48,112.97,158.95,104.10,107.97,104.62,101.02
2015-11-23,2086.590088,36.219639,12.120000,30.262524,81.309998,26.245783,125.029999,80.779999,130.077530,99.94,...,92.17,363.25,76.15,102.77,112.16,158.65,103.59,107.84,105.47,100.49
2015-11-24,2089.139893,36.515770,12.020000,30.507206,80.860001,26.781923,123.309998,80.389999,130.923172,99.26,...,93.13,356.81,75.62,102.04,113.19,157.75,103.40,107.35,105.49,99.41
2015-11-25,2088.870117,36.330700,11.900000,30.468054,81.709999,27.535873,124.160004,80.410004,130.608292,99.09,...,92.77,360.62,76.01,101.96,114.41,157.63,103.49,107.10,106.46,98.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-25,3298.459961,59.799999,157.720001,514.950012,271.089996,36.049999,482.880005,242.740005,138.210007,239.81,...,52.88,547.81,125.22,145.66,302.50,160.27,166.12,214.63,120.25,281.82
2020-09-28,3351.600098,59.580002,160.759995,521.400024,276.010010,36.389999,490.649994,246.669998,140.919998,240.00,...,53.98,558.65,128.55,147.11,303.23,161.66,168.90,222.78,121.74,284.14
2020-09-29,3335.469971,59.470001,164.809998,529.030029,276.929993,36.169998,493.480011,247.449997,138.550003,240.12,...,52.19,554.80,127.49,147.06,304.15,159.81,168.50,224.08,120.33,283.12
2020-09-30,3363.000000,59.700001,162.550003,541.219971,293.980011,36.700001,500.029999,251.320007,138.429993,241.73,...,51.84,563.55,128.22,148.88,311.77,160.18,166.63,225.99,122.08,277.56
2020-10-01,3380.800049,59.680000,168.490005,544.580017,290.049988,36.369999,527.510010,253.449997,138.220001,242.15,...,50.28,567.91,128.04,147.32,313.07,158.79,167.65,225.18,121.78,282.76

In [21]:
column_names = joint_portfolio.columns.values
column_names[0] = 'SP500'
joint_portfolio.columns = column_names


joint_portfolio.dropna(inplace=True)

joint_portfolio

,SP500,ORCL,SQ,NVDA,BABA,PFE,NFLX,CRM,GD,AMT,...,PSX,BLK,TROW,JNJ,UNH,MMM,UPS,ACN,PPG,NEE
2015-11-19,2081.239990,36.108597,13.070000,30.458263,77.870003,27.049994,120.220001,80.639999,130.626297,99.63,...,92.38,359.09,76.38,102.49,110.63,158.38,104.10,107.28,103.37,100.99
2015-11-20,2089.169922,36.404728,12.850000,30.722525,79.949997,26.957846,123.839996,80.989998,130.896194,100.49,...,91.67,362.46,76.37,102.48,112.97,158.95,104.10,107.97,104.62,101.02
2015-11-23,2086.590088,36.219639,12.120000,30.262524,81.309998,26.245783,125.029999,80.779999,130.077530,99.94,...,92.17,363.25,76.15,102.77,112.16,158.65,103.59,107.84,105.47,100.49
2015-11-24,2089.139893,36.515770,12.020000,30.507206,80.860001,26.781923,123.309998,80.389999,130.923172,99.26,...,93.13,356.81,75.62,102.04,113.19,157.75,103.40,107.35,105.49,99.41
2015-11-25,2088.870117,36.330700,11.900000,30.468054,81.709999,27.535873,124.160004,80.410004,130.608292,99.09,...,92.77,360.62,76.01,101.96,114.41,157.63,103.49,107.10,106.46,98.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-25,3298.459961,59.799999,157.720001,514.950012,271.089996,36.049999,482.880005,242.740005,138.210007,239.81,...,52.88,547.81,125.22,145.66,302.50,160.27,166.12,214.63,120.25,281.82
2020-09-28,3351.600098,59.580002,160.759995,521.400024,276.010010,36.389999,490.649994,246.669998,140.919998,240.00,...,53.98,558.65,128.55,147.11,303.23,161.66,168.90,222.78,121.74,284.14
2020-09-29,3335.469971,59.470001,164.809998,529.030029,276.929993,36.169998,493.480011,247.449997,138.550003,240.12,...,52.19,554.80,127.49,147.06,304.15,159.81,168.50,224.08,120.33,283.12
2020-09-30,3363.000000,59.700001,162.550003,541.219971,293.980011,36.700001,500.029999,251.320007,138.429993,241.73,...,51.84,563.55,128.22,148.88,311.77,160.18,166.63,225.99,122.08,277.56
2020-10-01,3380.800049,59.680000,168.490005,544.580017,290.049988,36.369999,527.510010,253.449997,138.220001,242.15,...,50.28,567.91,128.04,147.32,313.07,158.79,167.65,225.18,121.78,282.76

In [22]:
joint_portfolio.to_csv(r'combined_close_data_SP500_group_portfolio', index=True, header=True)